### PR TITLE
Fix PHP Warning and optimize _tag_indent()

### LINKED ISSUE #8: PHP message: PHP Warning:  Undefined array key "div" in /dokuwiki-test/lib/plugins/extlist/syntax.php on line 588
My setup:
OpenBSD 7.1 release, all patches applied, amd64, [`httpd(8)`](https://man.openbsd.org/OpenBSD-7.1/amd64/httpd.8), PHP-FPM 8.0.22, HTTP Basic authentication configured, DokuWiki 2022-07-31 "Igor".
The Wiki is a copy of an existing Wiki based on Hogfather upgraded to Igor according to the instructions (https://www.dokuwiki.org/install:upgrade).

Extended List Syntax Plugin 2016-07-26 is installed.

I am getting lots of PHP warnings like these:
```
PHP message: PHP Warning:  Undefined array key "div" in /dokuwiki-test/lib/plugins/extlist/syntax.php on line 588
PHP message: PHP Warning:  Undefined array key "/div" in /dokuwiki-test/lib/plugins/extlist/syntax.php on line 588
```

My fix was to modify the method `_tag_indent` in `/lib/plugins/extlist/syntax.php` to this:
```
	/**
	 * indent tags for readability if HTML source
	 *
	 * @param string $tag tag name
	 * @return array
	 */
	private function _tag_indent($tag)
	{
		// prefix and suffix of html tags
		$indent = [
			'ol'	=> ["\n","\n"],	'/ol'	=> ['',"\n"],
			'ul'	=> ["\n","\n"],	'/ul'	=> ['',"\n"],
			'dl'	=> ["\n","\n"],	'/dl'	=> ['',"\n"],
			'li'	=> ['  ',''],	'/li'	=> ['',"\n"],
			'dt'	=> ['  ',''],	'/dt'	=> ['',"\n"],
			'dd'	=> ['  ',"\n"],	'/dd'	=> ['',"\n"],
			'p'		=> ["\n",''],	'/p'	=> ['',"\n"],
			'div'	=> ["\n",''],	'/div'	=> ['',"\n"],
		];
		if (array_key_exists($tag, $indent))
			return $indent[$tag];

		return ['',''];
	}
```
Note: This includes the fix for the issue, correction of a spelling mistake and more modern and compact `array()` syntax. I also changed string literals to use `'` instead of `"` where possible.

Thanks!
fiwswe

### PR DESCRIPTION
**Pull request by fiwswe**
Fixes #8
See also PR #10 which fixes the same thing without the optimization and also fixes a number of other warnings.

### CODE REVIEW

**Comment by ssahara** [comment]
@fiwswe  I apologize very late response, and thanks your PR.
May I ask you to merge patch-2 into patch-1? I mean I prefer  `_tag_indent()` fix in patch-2 than #10 .

**Comment by fiwswe** [comment]
Done. I have been running essentially the same combined version for several months now without issues.

**Comment by ssahara** [comment]
@fiwswe , Would you mind updating version date in the plugin page?

**Comment by fiwswe** [comment]
Done.

I have also marked the plugin as compatible with Jack Jackrum and Igor. (Hogfather and some other older versions would probably be ok as well but I have not tested and don't want to install any of those old versions.)

BTW: Anyone can edit dokuwiki.org, even without login. But it is a bit nicer doing so as a logged in user. Gives the edit more credibility.

**Comment by ssahara** [comment]
Thanks!

**Pull request merged**
